[server]
pre_game_wait = 5
tick_wait_time = 5
terminal_map = false
log_dir = "logs"  # don't change during runtime
scores_file = "scores.log"

[game]
map_size = 20
max_score = 3
max_ticks = 200
capture_score = 5
kill_score = 1
winning_bonus = 10
home_flag_required = false
walls = 0   # Target integer number of walls (+- symmetries), or floating percentage of walls
actors = ["Runner", "Runner", "Runner"]

[[teams]]
name = "Team 1"
password = "1"

[[teams]]
name = "Team 2"
password = "2"

[[teams]]
name = "Team 3"
password = "3"

[[teams]]
name = "Team 4"
password = "4"

[image]
size = 980